#!/usr/bin/env php
<?php

// получаем список имен файлов из staging области
exec('git diff --cached --name-only', $stagedFiles);

$fixedFiles = [];
foreach ($stagedFiles as $fileName) {
    // проверяем только .php файлы
    // is_file - необходимо чтобы избежать проблем с переименованными и удаленными файлами, добавленными в комит.

    if (preg_match('/\.php$/', $fileName) && is_file($fileName)) {
        exec(sprintf('app/vendor/bin/php-cs-fixer fix %s -q', $fileName), $output, $exitCode);

        // 1 - этот код значит, что в файле были ошибки и они были исправлены
        if ($exitCode === 1) {
            // добавляем исправленный файл обратно в staging область
            exec('git add ' . $fileName);
            $fixedFiles [] = $fileName;
        }
    }
}

if (count($fixedFiles)) {
    echo sprintf("Code style fixes were applied to the following files:\n\n%s\n\nFiles were added to the commit after fixes.\n\n", implode("\n", $fixedFiles));
}

// allow commit
exit(0);
