migrations_namespace: 'App\Doctrine\Migrations\Log'
migrations_directory: 'src/Doctrine/Migrations/Log'
all_or_nothing: true
check_database_platform: false
table_name: 'migrations'
column_name: 'version'
executed_at_column_name: 'executed_at'
