doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'App\Doctrine\Migrations': '%kernel.project_dir%/src/Doctrine/Migrations'
    storage:
        table_storage:
            table_name: 'migrations'
            version_column_name: 'version'
            version_column_length: 1024
            executed_at_column_name: 'executed_at'
            execution_time_column_name: 'execution_time'
    all_or_nothing: true
