doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
        types:
            uuid: 'App\Doctrine\Dbal\Type\UuidType'
            email: 'App\Doctrine\Dbal\Type\EmailType'
            # Entity ---------------------------------------------------------------------------------------------------
            user_role: 'App\Model\User\Entity\RoleType'
            user_status: 'App\Model\User\Entity\StatusType'
            subdomain: 'App\Model\SubDomain\Entity\IdType'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/User/Entity'
                prefix: 'App\Model\User\Entity'
                alias: User
            Company:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Company/Entity'
                prefix: 'App\Model\Company\Entity'
                alias: Company
            SubDomain:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/SubDomain/Entity'
                prefix: 'App\Model\SubDomain\Entity'
                alias: SubDomain
