doctrine_migrations:
    migrations_paths:
        'App\Doctrine\Migrations\Core': 'src/Doctrine/Migrations/Core'
    storage:
        table_storage:
            table_name: 'migrations'
            version_column_name: 'version'
            executed_at_column_name: 'executed_at'
