doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_mysql
                url: '%env(DATABASE_URL)%'
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
            log:
                driver: pdo_mysql
                url: '%env(DATABASE_LOG_URL)%'
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
        types:
            uuid: 'App\Doctrine\Dbal\Type\UuidType'
            email: 'App\Doctrine\Dbal\Type\EmailType'
            # Entity ---------------------------------------------------------------------------------------------------
            user_role: 'App\Model\User\Entity\RoleType'
            user_status: 'App\Model\User\Entity\StatusType'
            subdomain: 'App\Model\SubDomain\Entity\IdType'
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                auto_mapping: false
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    User:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Model/User/Entity'
                        prefix: 'App\Model\User\Entity'
                        alias: User
                    Company:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Model/Company/Entity'
                        prefix: 'App\Model\Company\Entity'
                        alias: Company
                    SubDomain:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Model/SubDomain/Entity'
                        prefix: 'App\Model\SubDomain\Entity'
                        alias: SubDomain
            log:
                auto_mapping: false
                connection: log
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Log:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Model/Log/Entity'
                        prefix: 'App\Model\Log\Entity'
                        alias: Log